### ISSUE TITLE
extension in advanced app

### ISSUE THREAD

**Issue by thakkar-roshani** [yii2mod/yii2-cms#13]
Hi 
I am installing your extension in advanced app of yii. But i am getting error.

Can you please guide me how i can use it in advanced app? 
Please

**Comment by ihorchepurnyi** [comment]
Hi, try to the following steps
1 . `php composer.phar require --prefer-dist yii2mod/yii2-cms "*"`
2. When extension has been installed, you need to setup the [yii2mod-comments package](https://github.com/yii2mod/yii2-comments)
3. When done, you need to add the following code to this config [https://github.com/yiisoft/yii2-app-advanced/blob/master/backend/config/main.php](https://github.com/yiisoft/yii2-app-advanced/blob/master/backend/config/main.php)

```php
'id' => 'app-backend',
'controllerMap' => [
     'cms' => 'yii2mod\cms\controllers\CmsController',
],
```
> Now you can access to management section through the following URL:

http://your-backend-site-url/cms/index


4. When done, you need to add our custom page url class to `urlManager` section in your frontend config as follows:
```php
 'components' => [
     'urlManager' => [
         'rules' => [
             ['class' => 'yii2mod\cms\components\PageUrlRule'], // custom page url class
         ]
     ],
 ],
```

5, And the last step, you need to add the following code to SiteController in fronted app folder

```php
public function actions()
{
    return [
        'page' => [
            'class' => 'yii2mod\cms\actions\PageAction',
        ]
    ];
}
```

And now you can create your own pages via admin panel.

**Comment by deep12650** [comment]
@igor-chepurnoi I am getting forbidden 403 Forbidden error after installation.

**Comment by ihorchepurnyi** [comment]
Hi, @deep12650 

You need to create the user with `admin` role. Please, check this code - https://github.com/yii2mod/yii2-cms/blob/master/controllers/ManageController.php#L77

**Comment by deep12650** [comment]
Thanks @igor-chepurnoi. I will do that.

**Comment by zyber-envy** [comment]
Hi @igor-chepurnoi ,
I need quick help on these:
1. How do I set layout for only CMS Pages?
2. How do I change default URL shown in create page, or on clicking view from index? Actually I am using Advance template, I created a page from backend but when I click on page view it redirect me with admin url, I want show frontend Url.
Thanks,

**Comment by pptyasar** [comment]
I am not using RBAC, So how can I assign role? @igor-chepurnoi
