### ISSUE TITLE
problem on installing

### ISSUE THREAD

**Issue by RookieLittle** [yii2mod/yii2-cms#14]
hi, i'm a newbie on yii2. i am kinda confuse on the step of adding the code in the config files.
Would you mind to guide me step by step on this?

Sorry for any inconvenient and thank you.

**Comment by ihorchepurnyi** [comment]
Hi, do you install yii2-basic or advanced?

**Comment by RookieLittle** [comment]
Hi, i'm using advanced

**Comment by ihorchepurnyi** [comment]
Install steps:
1. Install the package: `php composer.phar require --prefer-dist yii2mod/yii2-cms "*"`
2. Execute migrations: `php yii migrate --migrationPath=@vendor/yii2mod/yii2-cms/migrations`
3. Setup Comments Extension:
    3.1 Execute migrations: `php yii migrate --migrationPath=@vendor/yii2mod/yii2-comments/migrations`
    3.2 Add this code to frontend/config/main.php
     ```php
        'modules' => [
             'comment' => [
                 'class' => 'yii2mod\comments\Module',
             ],
       ]
   ```
   3.3 Add this code to backend/config/main.php
      ```php
      'controllerMap' => [
             'comments' => 'yii2mod\comments\controllers\ManageController',
      ]  
      ```

4. Add this code to backend/config/main.php
```php
'modules' => [
    'admin' => [
        'controllerMap' => [
            'cms' => 'yii2mod\cms\controllers\CmsController',
       ],
    ],
],
```

5. Add this code to common/config/main.php
```php
 'components' => [
     'urlManager' => [
         'rules' => [
             ['class' => 'yii2mod\cms\components\PageUrlRule'],
         ]
     ],
 ],
```

6. Add this code to SiteController.php in folder frontend/controllers
```php
public function actions()
{
    return [
        'page' => [
            'class' => 'yii2mod\cms\actions\PageAction',
        ]
    ];
}
```

**And now you can create your own pages via admin panel.**
