### ISSUE TITLE
page builder

### ISSUE THREAD

**Issue by masihfathi** [yii2mod/yii2-cms#17]
is it possible to merge this extension "https://github.com/udokmeci/yii2-kont-trevor" to the core of yii2-cms and we have option to choose between simple editor and this page builder extension?

**Comment by ihorchepurnyi** [comment]
Hi, I think you can use `yii2-kont-trevor` package with `yii2mod-cms` together. You only need to create your own views and override this properties:
* https://github.com/yii2mod/yii2-cms/blob/master/controllers/ManageController.php#L30
* https://github.com/yii2mod/yii2-cms/blob/master/controllers/ManageController.php#L35

**Comment by masihfathi** [comment]
I think we should add a property to module.php which points enabling "yii2-kont-trevor" or not and for rendering "yii2-kont-trevor" in view changing 
"https://github.com/yii2mod/yii2-cms/blob/master/views/page.php" is necessary. how can i override module.php?

**Comment by ihorchepurnyi** [comment]
You need to override this property
* https://github.com/yii2mod/yii2-cms/blob/master/actions/PageAction.php#L26

**Comment by ihorchepurnyi** [comment]
```php
public function actions()
{
    return [
        'page' => [
            'class' => 'yii2mod\cms\actions\PageAction',
            'view'  => 'custom view',
        ]
    ];
}
```

**Comment by masihfathi** [comment]
thanks for replying.
