### ISSUE TITLE
upload and delete image problem

### ISSUE THREAD

**Issue by masihfathi** [yii2mod/yii2-cms#21]
thanks for your work in the yii2 mod, currently when i want to upload or delete image i got this error:
![method not allowed](https://user-images.githubusercontent.com/13271510/32196646-9ef36db4-bdd6-11e7-897e-052d0fe42cc4.png)

and user have admin permission but i got method not allowed error,
thanks in advance for your answer.

**Comment by masihfathi** [comment]
this problem is still available

**Comment by ihorchepurnyi** [comment]
Hi, I changed the version of froala editor and created the release, update please your package.

**Comment by masihfathi** [comment]
the error is still same, and i got "Failed to load resource: the server responded with a status of 405 (Method Not Allowed)" in the console when i want to upload picture

**Comment by masihfathi** [comment]
the problem not solved when i want to upload image by editor i got "http://localhost:8080/en/cms/manage/upload-image 405 (Method Not Allowed)" in the console. and for deleting image i got "jquery.js:9175 GET http://localhost:8080/en/cms/manage/delete-image 405 (Method Not Allowed)". i add get request to behavior method of manageController of your extension and now when i upload image via editor and print_r model errors i got:
Array
(
    [file] => Array
        (
            [0] => Please upload a file.
        )

)
{"link":"/files/attachment/0/0//_origin_."}
in the console.

**Comment by ihorchepurnyi** [comment]
I can't reproduce this issue, I tried to reproduce this issue on yii 2.0.13, php 7.1, Mysql 5.7

**Comment by ihorchepurnyi** [comment]
Also, I used my [template](https://github.com/yii2mod/base)

**Comment by masihfathi** [comment]
thanks for your help, i test yii2 mod base template with fresh install and every things work properly, i think, finally found my problem, i used "https://github.com/codemix/yii2-localeurls" for multi language and upload and delete image dose not work with other language and works properly with default language.

**Comment by masihfathi** [comment]
For other people who are experiencing same problem, they can use the following configurations in the url manager to exclude ajax urls:
```
     'ignoreLanguageUrlPatterns' => [
             '#^cms/manage/(upload-image|delete-image|images)#' => '#^cms/manage/(upload-image|delete-image|images)#',
       ]
```
